wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1667660297.898272
    t:
      1:
      - 55
      3:
      - 23
      4: 3.7.13
      5: 0.13.5
      8:
      - 1
      - 5
